### ISSUE TITLE
Deprecated: Creation of dynamic property TelegramBot\Entities\InlineKeyboardButton

### ISSUE THREAD

**Issue by essential-writer-codebase** [telegram-bot-php/core#10]
**PHP 8.3**

**For example if y send this **Request****

```
        Request::sendMessage([
            'chat_id' => $chat_id,
            'parse_mode' => ParseMode::MARKDOWN,
            'text' => "test message",
            'reply_markup' => InlineKeyboard::make()->setKeyboard([
                [
                    InlineKeyboardButton::make->setText("test")->setSwitchInlineQuery($message)
                ]
            ])
        ]);
```

**I haved this error:**
_Deprecated: Creation of dynamic property TelegramBot\Entities\InlineKeyboardButton::$text is deprecated_

**If i send this request with **setText()****

```
        Request::sendMessage([
            'chat_id' => $chat_id,
            'parse_mode' => ParseMode::MARKDOWN,
            'text' => "test message",
            'reply_markup' => InlineKeyboard::make()->setKeyboard([
                [
                    InlineKeyboardButton::make->setText("test")->setSwitchInlineQuery($message)
                ]

            ])
        ]);
```

**I haved this error:**
_Fatal error: Uncaught TypeError: TelegramBot\CrashPad::sendCrash(): Argument #3 ($update) must be of type ?string, false given, called in /var/www/vendor/telegram-bot-php/core/src/CrashPad.php on line 29 and defined in /var/www/vendor/telegram-bot-php/core/src/CrashPad.php:72 Stack trace: #0 /var/www/vendor/telegram-bot-php/core/src/CrashPad.php(29): TelegramBot\CrashPad::sendCrash() #1 [internal function]: TelegramBot\CrashPad::TelegramBot\{closure}() #2 {main} thrown in /var/www/vendor/telegram-bot-php/core/src/CrashPad.php on line 72_

**Comment by shahradelahi** [comment]
Hey @essential-writer-codebase,

There are a couple of use cases in the [tests/KeyboardTest.php](https://github.com/telegram-bot-php/core/blob/54119097853a21db174acad296498dcd8b76c64d/tests/KeyboardTest.php) file.

And the deprecation message is a warning message and can be ignored.
